name: Golang CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Run go fmt
        run: |
          fmt_result=$(gofmt -l .)
          if [ -n "$fmt_result" ]; then
            echo "Please run 'go fmt' on the following files:"
            echo "$fmt_result"
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
